<?php namespace Tai\Products;

use System\Classes\PluginBase;

class Plugin extends PluginBase
{
    public function registerComponents()
    {
        return [
          'Tai\Products\Components\Category' => 'categories',
          'Tai\Products\Components\ProductsComponent' => 'products_component',
          'Tai\Products\Components\CartComponent' => 'cart_component'
        ];
    }

    public function registerSettings()
    {
    }

    public function registerListColumnTypes()
    {
        return [
            'html' => function($value) { return str_limit( strip_tags($value), 150 ); }
        ]; // TODO: Change the autogenerated stub
    }


}
