<?php namespace Tai\Products;

use Illuminate\Support\Facades\Event;
use System\Classes\PluginBase;
use Tai\Products\Models\Products;

class Plugin extends PluginBase
{
    public function registerComponents()
    {
        return [
          'Tai\Products\Components\Category' => 'categories_component',
          'Tai\Products\Components\ProductsComponent' => 'products_component',
          'Tai\Products\Components\CartComponent' => 'cart_component'
        ];
    }

    public function registerSettings()
    {
    }

    public function registerListColumnTypes()
    {
        return [
            'html' => function($value) { return str_limit( strip_tags($value), 150 ); }
        ]; // TODO: Change the autogenerated stub
    }

    public function boot()
    {
        Event::listen('offline.sitesearch.query', function ($query) {

            // Search your plugin's contents
            $items = Products::where('name', 'like', "%${query}%")
                ->orWhere('description', 'like', "%${query}%")
                ->get();

            // Now build a results array
            $results = $items->map(function ($item) use ($query) {

                // If the query is found in the title, set a relevance of 2
                $relevance = mb_stripos($item->name, $query) !== false ? 2 : 1;

                return [
                    'title'     => $item->name,
                    'text'      => $item->description,
                    'url'       => '/shop/product/' . $item->slug,
                    'thumb'     => $item->product_image, // Instance of System\Models\File
                    'relevance' => $relevance, // higher relevance results in a higher
                    // position in the results listing
                    // 'meta' => 'data',       // optional, any other information you want
                    // to associate with this result
                ];
            });

            return [
                'provider' => 'Product', // The badge to display for this result
                'results'  => $results,
            ];
        });
    }


}
